#main.yml part of install role
- name: upload IOS-XE image if enough free space
  ios_command:
    commands:
      - command: "copy ftp://test:123456@1.1.1.1/{{ image_new }} flash:"
        prompt: '[confirm]'
        answer: ''

- name: install IOS-XE image
  ios_command:
    commands:
      - command: "request platform software package install switch all file flash:{{ image_new }} auto-copy"
      - command: 'reload'
        prompt: '[confirm]'
        answer: ''

- name: wait for device to come up
  wait_for_connection:
    delay: 30

- pause:
    seconds: 45

- name: software package clean
  ios_command:
    commands:
      # for this command to work prompt must be ']'
      - command: "request platform software package clean switch all file flash:"
        prompt: ']'
        answer: 'y'
